if(EXISTS "/home/zzk/MyData/miniob-2023/unittest/clog_test[1]_tests.cmake")
  include("/home/zzk/MyData/miniob-2023/unittest/clog_test[1]_tests.cmake")
else()
  add_test(clog_test_NOT_BUILT clog_test_NOT_BUILT)
endif()
