if(EXISTS "/home/zzk/MyData/miniob-2023/unittest/log_test[1]_tests.cmake")
  include("/home/zzk/MyData/miniob-2023/unittest/log_test[1]_tests.cmake")
else()
  add_test(log_test_NOT_BUILT log_test_NOT_BUILT)
endif()
