if(EXISTS "/home/zzk/MyData/miniob-2023/unittest/pidfile_test[1]_tests.cmake")
  include("/home/zzk/MyData/miniob-2023/unittest/pidfile_test[1]_tests.cmake")
else()
  add_test(pidfile_test_NOT_BUILT pidfile_test_NOT_BUILT)
endif()
